# Generated by Django 5.0.3 on 2024-04-30 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('not_fixed', 'not_fixed')], max_length=20)),
                ('days_per_week', models.IntegerField(choices=[(1, '1 Day/Week'), (2, '2 Days/Week'), (3, '3 Days/Week'), (4, '4 Days/Week'), (5, '5 Days/Week'), (6, '6 Days/Week'), (7, '7 Days/Week')])),
                ('required_qualification', models.CharField(choices=[('JSC', 'JSC'), ('SSC', 'SSC'), ('HSC', 'HSC'), ('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree'), ('PhD', 'PhD'), ('Other', 'Other Qualification')], max_length=20)),
                ('description', models.TextField()),
                ('class_of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.filter')),
            ],
        ),
    ]
