# Generated by Django 5.0.6 on 2024-10-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_tuitionpost_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionpost',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tuitionpost',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
