# Generated by Django 5.0.6 on 2024-10-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_tuitionpost_email_tuitionpost_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionpost',
            name='active',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
