# Generated by Django 5.0.6 on 2024-10-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_tuitionpost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionpost',
            name='subject',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
